# Generated by Django 5.2 on 2025-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(help_text="Установите дату оплаты", verbose_name="Дата оплаты"),
        ),
    ]
