# Generated by Django 5.2 on 2025-05-03 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribeUpdateCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_subscribe",
                    models.BooleanField(
                        default=True, help_text="Выберите статус подписки", verbose_name="Статус подписки"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Укажите курс, на который подписываетесь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribe",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя подписки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscribe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
