# Generated by Django 5.2 on 2025-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscribeupdatecourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribeupdatecourse",
            name="is_subscribe",
            field=models.BooleanField(
                default=False, help_text="Выберите статус подписки", verbose_name="Статус подписки"
            ),
        ),
    ]
