# Generated by Django 5.2 on 2025-05-03 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_subscribeupdatecourse_is_subscribe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribeupdatecourse",
            name="course",
            field=models.ForeignKey(
                help_text="Укажите курс, на который подписываетесь",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="subscribeupdatecourse",
            name="user",
            field=models.ForeignKey(
                help_text="Укажите пользователя подписки",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
