# Generated by Django 5.2.1 on 2025-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_subscribeupdatecourse_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Укажите дату обновления курса", verbose_name="Дата обновления"
            ),
        ),
    ]
